# Generated by Django 4.2.23 on 2026-08-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('raw_rows', models.PositiveIntegerField(default=0)),
                ('accepted_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('invalid_date_rows', models.PositiveIntegerField(default=0)),
                ('invalid_foreign_key_rows', models.PositiveIntegerField(default=0)),
                ('invalid_value_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('qty', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.CharField(max_length=32)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.importbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.store')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('mode', models.CharField(default='local', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics.assistantsession')),
            ],
        ),
    ]
